[[plugins]]
repo = 'vim-denops/denops.vim'
# important

[[plugins]]
repo = 'cocopon/iceberg.vim'
#color sheme

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

# ddc
[[plugins]]
repo = 'Shougo/ddc.vim'

# ddc ui
[[plugins]]
repo = 'Shougo/ddc-ui-native'

# ddc filter

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'

# ddc source
[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'Shougo/ddc-source-line'

[[plugins]]
repo = 'delphinus/ddc-ctags'

