[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'

# *ui*
# *filter*
# *source*

# *ui*
[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'
hooks_file = '$HOOK_DIR/ddc.vim'


# *filter*
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'
on_source = 'ddc.vim'

# *source*
[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'delphinus/ddc-ctags'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
depends = 'vim-lsp'
on_source = 'ddc.vim'

[[plugins]]

repo = 'uga-rosa/denippet.vim'
on_source = 'ddc.vim'
hooks_file = '$HOOK_DIR/denippet.vim'

