# *ui*
# *source*
# *filter*
# *kind*


# main
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hooks_file = '$HOOK_DIR/ddu.vim'

# ui
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'


[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'


# source
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = ['ddu.vim', 'ddu-kind-file']


# filter
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'


# kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

