hooks_file = '$HOOK_DIR/dein-ft.vim'


[[plugins]]
# important
repo = 'vim-denops/denops.vim'

[[plugins]]
# color scheme
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

# motion

# [[plugins]]
# repo = 'bkad/CamelCaseMotion'


