[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hooks_file = '$HOOK_DIR/vim-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depens = 'vim-lsp'

[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$HOOK_DIR/pum.vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'lambdalisue/vim-guise'

[[plugins]]
repo = 'vim-test/vim-test'
hooks_file = '$HOOK_DIR/vim-test.vim'

[[plugins]]
repo = 'tpope/vim-rake'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'bun913/min-todo.vim'

