[[plugins]]
repo = 'Shougo/ddc.vim'

# *ui*
# *filter*
# *source*

# *ui*
[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/pum.vim'

# *filter*
[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'

# *source*
[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'delphinus/ddc-ctags'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-mocword'

[[plugins]]
repo = 'uga-rosa/denippet.vim'
