[[plugins]]
repo = 'Shougo/ddc.vim'

# *ui*
# *filter*
# *source*

# *ui*
[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/pum.vim'

# *filter*
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'


# ddc source
[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'uga-rosa/denippet.vim'

[[plugins]]
repo = 'delphinus/ddc-ctags'
