[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'lambdalisue/vim-guise'

[[plugin]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/pum.vim'


