[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'lambdalisue/vim-guise'

[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-rake'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'khorser/vim-mercury'
